In [6]:
import pandas as pd
import os

# 定义文件夹路径
folder_path = "/Users/laihuiqian/weibo/all_data/all_data_2022/2022_data"

# 初始化一个空的DataFrame，用于存储所有的数据
all_data = []

# 遍历文件夹中的所有Excel文件
for file in os.listdir(folder_path):
    if file.endswith('.xlsx'):
        file_path = os.path.join(folder_path, file)
        
        # 读取Excel文件
        df = pd.read_excel(file_path, engine='openpyxl')
        
        # 将所有的列堆叠起来形成一个单一的列
        stacked_values = df.stack().reset_index(drop=True)
        
        # 追加到总的数据列表中
        all_data.append(stacked_values)

# 合并所有数据到一个DataFrame
df_total = pd.concat(all_data, ignore_index=True)

# 重命名列名
df_total.columns = ['Values']

# 展示头部内容
print(df_total.head())


/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


0    【直播预告｜年度爱用盘点（下）】趁热打铁，下期来啦！🏃♀️清洁｜氨基酸洁面慕斯•口腔冲牙器滋...
1    最好的礼物从来不是礼物本身而是意料之中的温暖和出其不意的惊喜💫#新年礼物已就位##上新了新年...
2    2022年最后一天必须抽“红包”呀㊗️大家新年红红火火～平安健康～🧨留言里揪3⃣️0⃣️位哦...
3    妆容变化！3年的变美逆袭秘诀[哇][哇]几个美妆技巧 就可以改变妆容！底妆——眼妆——中庭—...
4    贵气美女的养成茂密的头发和好皮肤才是关键哦喜欢熬夜的妹妹们看看这里～#爱用##好物分享#  ...
dtype: object


In [7]:
import lda
import pandas as pd
import jieba
import numpy as np

def open_dict(Dict):
    path = '%s.txt' % Dict
    dictionary = open(path, 'r', encoding='utf-8')
    dict = []
    for word in dictionary:
        word = word.strip('\n')
        dict.append(word)
    return dict

clearwords=open_dict('clearwords')

def chinese_word_cut(mytext):
    tempcut = jieba.cut(str(mytext))
    result = " ".join(set(tempcut) - set(clearwords))
    return result if result.strip() else np.nan

print(df_total)
df_total["content_cutted"] = df_total.apply(chinese_word_cut)
n_features = 10000

0        【直播预告｜年度爱用盘点（下）】趁热打铁，下期来啦！🏃♀️清洁｜氨基酸洁面慕斯•口腔冲牙器滋...
1        最好的礼物从来不是礼物本身而是意料之中的温暖和出其不意的惊喜💫#新年礼物已就位##上新了新年...
2        2022年最后一天必须抽“红包”呀㊗️大家新年红红火火～平安健康～🧨留言里揪3⃣️0⃣️位哦...
3        妆容变化！3年的变美逆袭秘诀[哇][哇]几个美妆技巧 就可以改变妆容！底妆——眼妆——中庭—...
4        贵气美女的养成茂密的头发和好皮肤才是关键哦喜欢熬夜的妹妹们看看这里～#爱用##好物分享#  ...
                               ...                        
17625    昨天出去玩嘛，凌晨回到家我朋友跟我说的第一句话是：天啦这个底妆怎么会到现在还这么完整一点都没...
17626                                     2022的第二天也美美出门啦！ 
17627                                          2022 远离烦恼🥳 
17628    救命！！🆘\n这个下睫毛也太好看了吧！！\n也是胖给我推荐的，之前买分段式小恶魔睫毛那家16...
17629                   2021年的遗憾不开心都过去啦！！\n2022很崭新，要快乐噢！！ 
Length: 17630, dtype: object


/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [8]:
df_total["content_cutted"] = df_total["content_cutted"].dropna()
print(df_total)
print(df_total["content_cutted"])

0                 【直播预告｜年度爱用盘点（下）】趁热打铁，下期来啦！🏃♀️清洁｜氨基酸洁面慕斯•口腔冲牙器滋...
1                 最好的礼物从来不是礼物本身而是意料之中的温暖和出其不意的惊喜💫#新年礼物已就位##上新了新年...
2                 2022年最后一天必须抽“红包”呀㊗️大家新年红红火火～平安健康～🧨留言里揪3⃣️0⃣️位哦...
3                 妆容变化！3年的变美逆袭秘诀[哇][哇]几个美妆技巧 就可以改变妆容！底妆——眼妆——中庭—...
4                 贵气美女的养成茂密的头发和好皮肤才是关键哦喜欢熬夜的妹妹们看看这里～#爱用##好物分享#  ...
                                        ...                        
17626                                              2022的第二天也美美出门啦！ 
17627                                                   2022 远离烦恼🥳 
17628             救命！！🆘\n这个下睫毛也太好看了吧！！\n也是胖给我推荐的，之前买分段式小恶魔睫毛那家16...
17629                            2021年的遗憾不开心都过去啦！！\n2022很崭新，要快乐噢！！ 
content_cutted    0        舒缓 冲牙器 用 ， 口腔 🏃 氨基酸 乳 防护 啦 霜 次 豆豆 来 直...
Length: 17631, dtype: object
0        舒缓 冲牙器 用 ， 口腔 🏃 氨基酸 乳 防护 啦 霜 次 豆豆 来 直播 精华   ｜ ...
1        而是 新年礼物 [ 张 了 ] 共 上 新 新年 本身     💫 已 从来不 和 最好 温...
2        [ 揪 ㊗ 大家 ⃣ ] 新年   抽奖   ～ ！ “ 平安 ” 位 ️ 0 里 3 哦 ...
3        可以 秘诀 独门 [ ] 几个   — 改变 起来 快学 王宛尘 唇妆 瑕

/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [25]:
# 加载本地目录下的停用词文件
with open('cn_stopwords.txt', 'r', encoding='utf-8') as f:
    chinese_stopwords = [line.strip() for line in f]

# 其余代码保持不变

from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
import pyLDAvis
import pyLDAvis.sklearn

tf_vectorizer = CountVectorizer(strip_accents = 'unicode',
                                max_features=n_features,
                                stop_words=chinese_stopwords,  # 使用加载的中文停用词
                                max_df = 0.6,
                                min_df = 10)

tf = tf_vectorizer.fit_transform(df_total["content_cutted"])
vocab=tf_vectorizer.get_feature_names_out()
model = lda.LDA(n_topics=17, n_iter=100, random_state=44)  
model.fit(tf)
print('model done')

# 主题-单词（topic-word）分布
topic_word = model.topic_word_ 
print("shape: {}".format(topic_word.shape))
print(vocab[:3])
print(topic_word[:, :3])
for n in range(10):
    sum_pr = sum(topic_word[n,:])  
    print("topic: {} sum: {}".format(n, sum_pr))

# 计算各主题Top-N个单词
import numpy as np
n = 20
for i, topic_dist in enumerate(topic_word):  
    topic_words = np.array(vocab)[np.argsort(topic_dist)][:-(n+1):-1]  
    print('*Topic {}\n- {}'.format(i, ' '.join(topic_words)))

# # 计算每个文档的主题分布
# doc_topic_dist = model.transform(tf)

# # 对于每篇文档，找到其最可能的主题
# doc_main_topic = np.argmax(doc_topic_dist, axis=1)

# # 统计每个主题的文档数量
# topic_counts = np.bincount(doc_main_topic)

# # 计算每个主题在所有文档中的比例
# total_docs = len(doc_main_topic)
# topic_percentages = (topic_counts / total_docs) * 100

# # 主题-单词（topic-word）分布
# topic_word = model.topic_word_ 

# # 计算各主题Top-N个单词并统计出现次数与占比
# n = 20
# for i, topic_dist in enumerate(topic_word):  
#     topic_words = np.array(vocab)[np.argsort(topic_dist)][:-(n+1):-1]
    
#     # 统计每个关键词在文档中的出现次数
#     word_counts = {}
#     for word in topic_words:
#         word_counts[word] = sum(df_total["content_cutted"].apply(lambda x: word in x))
    
#     # 计算每个关键词的占比
#     total_word_counts = sum(word_counts.values())
#     word_percentages = {}
#     for word, count in word_counts.items():
#         word_percentages[word] = (count / total_word_counts) * 100
    
#     # 打印每个主题的关键词、出现次数和占比
#     print('*Topic {}'.format(i))
#     for word in topic_words:
#         print('- {}: count = {}, percentage = {:.2f}%'.format(word, word_counts[word], word_percentages[word]))
    
#     # 打印每个主题的文档数量和占比
#     print('Topic {} total counts = {}, percentage = {:.2f}%\n'.format(i, topic_counts[i], topic_percentages[i]))



/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
INFO:lda:n_documents: 17630
INFO:lda:vocab_size: 7420
INFO:lda:n_words: 412330
INFO:lda:n_topics: 17
INFO:lda:n_iter: 100
INFO:lda:<0> log likelihood: -5198063
INFO:lda:<10> log likelihood: -3793869
INFO:lda:<20> log likelihood: -3595791
INFO:lda:<30> log likelihood: -3524539
INFO:lda:<40> log likelihood: -3486108
INFO:lda:<50> log likelihood: -3463362
INFO:lda:<60> log likelihood: -3446567
INFO:lda:<70> log likelihood: -3436532
INFO:lda:<80> log likelihood: -3427439
INFO:lda:<90> log likelihood: -3421756
INFO:lda:<99> log likelihood: -3418031


model done
shape: (17, 7420)
['01' '02' '03']
[[6.43575189e-07 6.43575189e-07 6.43575189e-07]
 [4.37958762e-07 4.37958762e-07 4.37958762e-07]
 [5.00545595e-07 5.00545595e-07 5.00545595e-07]
 [7.48919779e-04 7.48919779e-04 3.49762002e-04]
 [6.05759562e-07 6.05759562e-07 6.05759562e-07]
 [4.90865002e-07 4.90865002e-07 4.90865002e-07]
 [2.96426285e-07 2.96426285e-07 2.96426285e-07]
 [5.55827293e-07 5.55827293e-07 5.55827293e-07]
 [5.22296853e-07 5.22296853e-07 5.22296853e-07]
 [9.59257313e-04 3.55148949e-07 3.55148949e-07]
 [7.20398813e-07 7.20398813e-07 7.20398813e-07]
 [3.33765003e-07 3.33765003e-07 3.33765003e-07]
 [2.14021856e-07 2.14021856e-07 2.14021856e-07]
 [4.48346051e-07 4.48346051e-07 4.48346051e-07]
 [1.08276026e-03 1.15492023e-03 1.08276026e-03]
 [2.53336441e-07 2.53336441e-07 2.53336441e-07]
 [5.20042435e-07 5.20042435e-07 5.20042435e-07]]
topic: 0 sum: 1.0000000000000657
topic: 1 sum: 1.00000000000005
topic: 2 sum: 1.0000000000001528
topic: 3 sum: 0.9999999999998751
topic: 

In [17]:
from sklearn.cluster import AgglomerativeClustering

# 创建聚类模型实例
clustering_model = AgglomerativeClustering(n_clusters=10)

# 应用聚类模型
clustering_model.fit(topic_word)

# 获取聚类标签
cluster_labels = clustering_model.labels_

# 初始化新的主题-单词矩阵
new_topic_word = np.zeros((10, topic_word.shape[1]))

# 根据聚类结果创建新的主题-单词分布
for i in range(10):
    # 获取当前聚类的主题索引
    topic_indices = np.where(cluster_labels == i)[0]
    # 计算这些主题的平均单词分布
    new_topic_word[i] = np.mean(topic_word[topic_indices], axis=0)


/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [9]:
# 计算新的10个主题的Top-20个单词
n = 22
for i, topic_dist in enumerate(new_topic_word):  
    topic_words = np.array(vocab)[np.argsort(topic_dist)][:-(n+1):-1]  
    print('*New Topic {}\n- {}'.format(i, ' '.join(topic_words)))


/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


NameError: name 'new_topic_word' is not defined

In [9]:
from sklearn.cluster import AgglomerativeClustering

# 创建聚类模型实例
clustering_model = AgglomerativeClustering(n_clusters=10)

# 应用聚类模型
clustering_model.fit(topic_word)

# 获取聚类标签
cluster_labels = clustering_model.labels_

# 初始化新的主题-单词矩阵
new_topic_word = np.zeros((10, topic_word.shape[1]))

# 根据聚类结果创建新的主题-单词分布
for i in range(10):
    # 获取当前聚类的主题索引
    topic_indices = np.where(cluster_labels == i)[0]
    # 计算这些主题的平均单词分布
    new_topic_word[i] = np.mean(topic_word[topic_indices], axis=0)

# 计算新的10个主题的Top-20个单词及其出现次数和占比
n = 20
for i, topic_dist in enumerate(new_topic_word):  
    topic_words = np.array(vocab)[np.argsort(topic_dist)][:-(n+1):-1]
    
    # 统计每个关键词在文档中的出现次数
    word_counts = {}
    for word in topic_words:
        word_counts[word] = sum(df_total["content_cutted"].apply(lambda x: word in x))
    
    # 计算每个关键词的占比
    total_word_counts = sum(word_counts.values())
    word_percentages = {}
    for word, count in word_counts.items():
        word_percentages[word] = (count / total_word_counts) * 100
    
    # 打印每个主题的关键词、出现次数和占比
    print('*New Topic {}'.format(i))
    for word in topic_words:
        print('- {}: count = {}, percentage = {:.2f}%'.format(word, word_counts[word], word_percentages[word]))
    
    # 打印每个主题的文档数量和占比
    print('New Topic {} total counts = {}, percentage = {:.2f}%\n'.format(i, topic_counts[i], topic_percentages[i]))


/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


*New Topic 0
- 妆容: count = 1516, percentage = 7.10%
- 夏日: count = 1038, percentage = 4.86%
- 分享: count = 3129, percentage = 14.65%
- 美妆: count = 2166, percentage = 10.14%
- 搭配: count = 799, percentage = 3.74%
- 好看: count = 770, percentage = 3.60%
- 姐妹: count = 1717, percentage = 8.04%
- 化妆: count = 826, percentage = 3.87%
- 适合: count = 1175, percentage = 5.50%
- 颜色: count = 438, percentage = 2.05%
- ootd: count = 398, percentage = 1.86%
- 口红: count = 546, percentage = 2.56%
- 喜欢: count = 1356, percentage = 6.35%
- 眼影: count = 460, percentage = 2.15%
- 氛围: count = 911, percentage = 4.26%
- 日常: count = 1492, percentage = 6.98%
- 变美: count = 603, percentage = 2.82%
- 简单: count = 460, percentage = 2.15%
- 精致: count = 591, percentage = 2.77%
- 夏天: count = 974, percentage = 4.56%
New Topic 0 total counts = 889, percentage = 5.04%

*New Topic 1
- 皮肤: count = 1456, percentage = 7.36%
- 肌肤: count = 1024, percentage = 5.18%
- 效果: count = 931, percentage = 4.71%
- 头发: count = 373, percentage = 1.